### ISSUE TITLE
Any plans for WAL2 / BEGIN CONCURRENT?

### ISSUE THREAD

**Issue by gnat** [proofrock/ws4sqlite#30] opened 2023-05-02 07:22 UTC
Firstly, awesome project! 👏 Love the backup / vacuum jobs and driver-free access via http! Very flexible tool.

WAL2 would provide some nice advantages to ws4sqlite:

* More concurrent writes per second without batching.
* No infinitely growing WAL file.
* No writing until **COMMIT**.
* More granular "page level" locking (instead of "table level" with WAL).

**Comment by proofrock** [comment] 2023-05-02 11:38
Thanks! I'll mark this as duplicate of #31

**Closed by proofrock** 2023-05-02 11:38 UTC
Labels: duplicate
